name: Test site
version: 1.0.0
meta:
  createdAt: 2024-12-23T02:34:30.847Z
  updatedAt: 2024-12-23T02:34:30.847Z
  author: ''
  description: ''
pages:
  - id: home
    name: Home
    path: /
customDomain: grapevyn.app
